### ISSUE TITLE
Nameplate Sizing

### ISSUE THREAD

**Issue by DatFluffySheep** [josephcyang4459/Duo-Darts#52]
When speaking to certain characters, for example "Charming Girl", their name can't fit into the name bar so it spills off the screen, needs to be resized. Another example is  "Bathroom Wall"

**Comment by DatFluffySheep** [comment]
Lounge Guy is not fixed yet

**Comment by josephcyang4459** [comment]
Just did a little bit of trouble-shooting on this to fix. I'm not too sure what the aspect ratio is for the game. Judging by the screen size resolution, the aspect ratio should be 16:9.

This could be fixed by changing the "Auto Size" property. It can also be fixed by changing the aspect ratio when testing the game through the "Game" Window. Look below for more info.


![Image](https://github.com/josephcyang4459/Duo-Darts/assets/65678477/46ea3b59-9e3b-4718-a9ee-b30c7cc31b76)




![Image](https://github.com/josephcyang4459/Duo-Darts/assets/65678477/8bc3570d-c454-4ff1-931d-18b5ba0a0525)
